version: 2
jobs:
  build:
    docker:
      - image: python:3.5
  steps:
    - checkout

    - name: Install dependencies
      command: pip install -r requirements.txt

deployment:
  production:
    branch: master
    heroku:
      appname: flask-demo