version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"

      - run:
          name: Deploy to Heroku
          command: |
            ./setup-heroku.sh
            git push heroku HEAD:master
